### ISSUE TITLE
Domain expired

### ISSUE THREAD

**Issue by Purukitto** [Purukitto/PikaServe#20]
domain will be renewed soon

**Comment by kaldray** [comment]
hi , do you know when the domain will be reneweb ?

**Comment by Purukitto** [comment]
@kaldray Having some money issues, so as soon as I can get around that I will renew the domain

**Comment by SaidAlizade** [comment]
Any update on the domain?

**Comment by Purukitto** [comment]
> Any update on the domain?

It would be back up by next month
